### ISSUE TITLE
some question about your code?

### ISSUE THREAD

**Issue by youngfly11** [XiangChenchao/DDPN#1]
I am confused how the $n.cvec$ work in the lstm?   Hope for your reply, thanks

> n.lstm1 = L.LSTM(\
                   word_emb, n.cvec,\
                   recurrent_param=dict(\
                       num_output=cfg.RNN_DIM,\
                       weight_filler=dict(type='xavier')))

**Comment by WenjianDong** [comment]
It looks like it is a flag for non-padding words. [https://github.com/XiangChenchao/DDPN/blob/master/data_provider/data_provider.py#L95](url)
`def str2list(self, qstr, query_maxlen):
        q_list = qstr.split()
        qvec = np.zeros(query_maxlen, dtype=np.int64)
        cvec = np.zeros(query_maxlen, dtype=np.int64)
        for i,_ in enumerate(xrange(query_maxlen)):
            if i < query_maxlen - len(q_list):
                cvec[i] = 0
            else:
                w = q_list[i-(query_maxlen-len(q_list))]
                # is the word in the vocabulary?
                # if self.qdic.has_token(w) is False:
                #     w = cfg.UNK_WORD    #'<unk>'
                qvec[i] = self.qdic.lookup(w)
                cvec[i] = 0 if i == query_maxlen - len(q_list) else 1

return qvec, cvec`

For the reason why the author does this, I am also confused.

**Comment by youngfly11** [comment]
Thank you for reply @WenjianDong. I have figured it out.
1. $cvec$ is the binary vector, which indicate whether the current memory information  $c_i$ in lstm passed into next time step. You can check the lstm source code in caffe.
2. Because, the author use batch sample to train the network. So they need to pad the phrases into the same length. The $cvec$ here can stop padded word information to pass it into next word.

**Comment by WenjianDong** [comment]
Indeed. Thank you for your reply @youngfly11
